name: "Build my JAVA Application"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1/ Récupération des sources
      # 2/ Builder notre jar avec maven
      # 3/ Sauvegarder notre jar en tant qu'artefact
      - name: Récupération du code source (git clone)
        uses: actions/checkout@v3
      - name: Prépare un environnement d execution java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Builder notre projet avec maven
        run: mvn package
      - name: "Stocker le jar en tant qu'artefact"
        uses: actions/upload-artifact@v3
        with:
          name: project-jar
          path: target/*.jar
